inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

# Notify uses address_line_1 etc naming convention and we want to align with it
Naming/VariableNumber:
  Enabled: false

# Disable this cop to avoid having to rewrite all uses of update_all
Rails/SkipsModelValidations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
  # This cop is n/a for rake tasks
    - spec/lib/tasks/*
  # Allow more descriptive string labels for request specs
    - spec/requests/**/*

# Using 'let(:registration1)' in a unit test isn't necessarily unreasonable.
RSpec/IndexedLet:
  Enabled: false

# rubocop-rspec 2.16.0 introduced a false positive: https://github.com/rubocop/rubocop-rspec/issues/1520
# TODO: Remove this after the next rubocop-rspec release is bundled
RSpec/PendingWithoutReason:
  Exclude:
    - spec/factories/*
    - spec/helpers/*
