inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-rails
  - rubocop-rspec
# Disable this cop to avoid having to rewrite all uses of update_all
Rails/SkipsModelValidations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
