inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2.2

Lint/DuplicateMethods:
  Exclude:
    # This cop seems to trip over a combination of a delegate instruction for an attribute/method and a call to the original attribute/method
    - app/presenters/reports/boxi/registration_presenter.rb

# Notify uses address_line_1 etc naming convention and we want to align with it
Naming/VariableNumber:
  Enabled: false

# Bad cop: Not all methods returning a boolean should end in a question mark.
# For example `submit_form` is a directive, not a query, and the boolean response indicates success or failure.
Naming/PredicateMethod:
  Enabled: false

# Aligning with this cop would require excessive refactoring
Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    # This cop is n/a for rake tasks
    - spec/lib/tasks/*
    # Allow more descriptive string labels for request specs
    - spec/requests/**/*
    # Not applicable for feature specs
    - spec/features/**/*

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true
  AllowedCops:
    - Layout/LineLength
    - Lint/DuplicateMethods                # this cop raises a bogus alert for boxi presenter finance_details_balance
    - Lint/PercentStringArray              # ['foo'] style is required for secure headers configuration
    - Metrics/AbcSize
    - Metrics/BlockLength
    - Metrics/ClassLength
    - Metrics/MethodLength
    - Metrics/ModuleLength
    - Naming/MemoizedInstanceVariableName  # this cop sometimes fires when we're not actually memoizing
    - Rails/Output                         # we sometimes want to write to stdout so we can see Rake task output on Jenkins
    - Rails/SkipsModelValidations          # we want to keep using update_all in certain circumstances
    - RSpec/ContextWording                 # it sometimes suits to use non-standard context phrasing for clarity
    - RSpec/ExpectOutput                   # this cop fires when we just want to suppress stdout output during unit tests
    - RSpec/LetSetup
  
