inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2

# Notify uses address_line_1 etc naming convention and we want to align with it
Naming/VariableNumber:
  Enabled: false

# Aligning with this cop would require excessive refactoring
Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    # This cop is n/a for rake tasks
    - spec/lib/tasks/*
    # Allow more descriptive string labels for request specs
    - spec/requests/**/*
    # Not applicable for feature specs
    - spec/features/**/*

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true
  AllowedCops:
    - Layout/LineLength
    - Lint/PercentStringArray              # ['foo'] style is required for secure headers configuration
    - Metrics/AbcSize
    - Metrics/BlockLength
    - Metrics/ClassLength
    - Metrics/MethodLength
    - Metrics/ModuleLength
    - Naming/MemoizedInstanceVariableName  # this cop sometimes fires when we're not actually memoizing
    - Rails/Output                         # we sometimes want to write to stdout so we can see Rake task output on Jenkins
    - Rails/SkipsModelValidations          # we want to keep using update_all in certain circumstances
    - RSpec/ContextWording                 # it sometimes suits to use non-standard context phrasing for clarity
    - RSpec/ExpectOutput                   # this cop fires when we just want to suppress stdout output during unit tests
    - RSpec/LetSetup
  
