inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-rails
  - rubocop-rspec

# Notify uses address_line_1 etc naming convention and we want to align with it
Naming/VariableNumber:
  Enabled: false

# Disable this cop to avoid having to rewrite all uses of update_all
Rails/SkipsModelValidations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
# This cop is n/a for rake tasks
    - spec/lib/tasks/*
# Allow more descriptiive strings for request specs
    - spec/requests/**/*

# TODO Revisit these over time
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
