---
new_registration:
  active: <%= ENV["FEATURE_TOGGLE_NEW_REGISTRATION"] %>
api:
  active: <%= ENV["FEATURE_TOGGLE_API"] %>
renewal_reminders:
  active: <%= ENV["FEATURE_TOGGLE_RENEWAL_REMINDERS"] %>
send_digital_renewal_sms:
  active: <%= ENV["FEATURE_TOGGLE_SEND_DIGITAL_RENEWAL_SMS"] %>
