---
new_registration:
  active: <%= ENV["FEATURE_TOGGLE_NEW_REGISTRATION"] %>
api:
  active: <%= ENV["FEATURE_TOGGLE_API"] %>
renewal_reminders:
  active: <%= ENV["FEATURE_TOGGLE_RENEWAL_REMINDERS"] %>
use_extended_grace_window:
  active: <%= ENV["USE_EXTENDED_GRACE_WINDOW"] %>
