development:
  # Configure available database clients. (required)
  clients:
    # Config for the registrations database
    default:
      database: <%= ENV['EMS_DB_NAME'] || 'entity-matching-service' %>
      hosts:
        - <%= ENV['EMS_DB_URL1'] || 'localhost:27017' %>
      options:
        user: <%= ENV['EMS_DB_USERNAME'] || 'mongoUser' %>
        password: <%= ENV['EMS_DB_PASSWORD'] || 'password1234' %>
test:
  clients:
    default:
      database: <%= ENV['EMS_TEST_DB_NAME'] || 'entity-matching-service-test' %>
      hosts:
        - <%= ENV['EMS_TEST_DB_URL1'] || 'localhost:27017' %>
      options:
        user: <%= ENV['EMS_TEST_DB_USERNAME'] || 'mongoUser' %>
        password: <%= ENV['EMS_TEST_DB_PASSWORD'] || 'password1234' %>
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
