# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 795bb39d72d2ccfe9b1d033c8bc5380f21daca0fc61e2ed9bc75481799ef8ea926e8b15d24dfc9c0dd23c5662c7e712c8535d8b431cd78d3ef25ad16afcf0e74

test:
  secret_key_base: 461c07a73cc5ce47f8408295abc0f46ebf8992e8866db223ee66643e11b341a015e38f5ff61207cea564f29f946f90f462be580383f7058970d0d1ae0984c102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
